language: generic
before_install: true
install: true
before_script: echo "Before Script"
script: if [ "$TRAVIS_PULL_REQUEST" == false ]; then bash ./deploy.sh; fi
deploy:
  provider: azure_web_apps
  username: $USERNAME
  password: $PASSWORD
  site: "dl-ui-dev"