language: generic
before_install: true
install: true
before_script: echo "Before Script"
script: bash ./deploy.sh
deploy:
  provider: azure_web_apps
  username: $USERNAME
  password: $PASSWORD
  site: "dl-ui-dev"